apiVersion: v1
kind: Service
metadata:
  name: text4shell
  labels:
    app: text4shell
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  selector:
    app: text4shell
